const constants = {
  SORT_COLORS: "SORT_COLORS",
  SORTED_BY_DATE: "SORTED_BY_DATE",
  SORTED_BY_TITLE: "SORTED_BY_TITLE",
  SORTED_BY_RATING: "SORTED_BY_RATING",
  ADD_COLOR: "ADD_COLOR",
  CHANGE_COLOR: "CHANGE_COLOR",
  RATE_COLOR: "RATE_COLOR",
  RENAME_COLOR: "RENAME_COLOR",
  REMOVE_COLOR: "REMOVE_COLOR",
  ADD_TOAST: "ADD_TOAST",
  REMOVE_TOAST: "REMOVE_TOAST",
}

export default constants